### ISSUE TITLE
Make sure you can install plugin with no direct input

### ISSUE THREAD

**Issue by malukenho** [codelicia/xulieta#97]

**Comment by EHER** [comment]
It is working fine in a internal project running on Gitlab CI.

The pipeline is running a composer image and adding xulieta and json plugin like this:

```yaml
xulieta:
  stage: test
  image: composer:2.2.6
  script:
    - composer require codelicia/xulieta
    - composer require codelicia/xulieta-json
    - vendor/bin/xulieta check:erromeu -v .

```
